ChainID = '534353'
FinalityDepth = 1
LogPollInterval = '3s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'
OCR.ContractConfirmations = 1

[GasEstimator]
Mode = 'L2Suggested'
# Scroll uses the L2Suggested estimator; we don't want to place any limits on the minimum gas price
PriceMin = '0'
# Never bump gas on optimism
BumpThreshold = 0

[GasEstimator.BlockHistory]
# Force an error if someone enables the estimator by accident; we never want to run the block history estimator on Scroll
BlockHistorySize = 0

[HeadTracker]
HistoryDepth = 50
